version: 2

# Required when source tree is not copied in a directory called ldap2pg
project_name: ldap2pg

builds:
- main: .
  env:
  - CGO_ENABLED=0
  flags:
  - -pgo=default.pgo
  gcflags:
  - -trimpath -buildvcs
  goarch:
  - amd64
  - arm64
  goos:
  - linux
  - windows
  - darwin
  ignore:
  - goos: windows
    goarch: arm64

changelog:
  disable: true

nfpms:
- formats:
  - deb
  - rpm
  - apk
  maintainer: "Étienne BERSAC <contact@dalibo.com>"
  description: Manage PostgreSQL roles and privileges from YAML or LDAP
  vendor: "Dalibo"
  homepage: "https://labs.dalibo.com/ldap2pg"
  license: "PostgreSQL"

release:
  prerelease: auto

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
